language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: stanczakdominik
  password:
    secure: hwwtc2kliYrnYwpuyk2xkCOi/nl+vqg9g5H+GREd4MFlu2LYp0M6YoCTOCrwUSgmjVSs8jwirNz0jvlTaLb4g4RVYzgLPnslrT3BGulbXOEkOBTi+AeLF435nvSXQ0S62iQ5Ywi1JOmsaEiX+wg1NQBcoxtsTx5SOCyv0nvpmkGxaX5lAOzkS/JFo73ESAqb+LcQowQSkFBveswMPhqpxO23brtt4954O8hOpgLjAYOyzGorhM21U1z9DyWc1nr1zYVBZlqAZDUd9zVOUzlyCMSqov1nJUWiXJaNxqHez4BAjusXgwulmWcGmquSCSWLO9m03E+nkOp9cJS1O6oJS48NeNos3AwhVDZC6kDJHE74JcAHZij9T+Udn5E9TzUglUYZJDK9QxLVmDHJg6fw0MCeqU+LYfrjBTddvqOwIrBFI8+idzhE++ZoFnDdnj5oLoG9nTkd0PR3CgPHE8pN5CzlSELpUd/sD6Um0Yk/QnJiXnqwZ+4r7whHQuqJD5xZBkjvljNF8cYV8N1m1CYp/q3xpvQWaUJsD3L6iMBTXIp3Or3g5+O1kVjge4B+PAcYccsYc9KGDQsMrQ2H/ESPwWgX6t338Un4KCF6fLpInTI9sbhwIjAcGbVJU155cEaz89xQje+Oxe/eXj9SIt8WSoHKY4qXCxXSBmrhdrbNo70=
  on:
    tags: true
    repo: StanczakDominik/sc2replaystats_uploader
    python: 3.8
